services:
  api-gateway:
    profiles: ["placeholder"]

  car-configurator:
    profiles: ["placeholder"]

  merch-shop:
    profiles: ["placeholder"]

  ai-feature:
    profiles: ["placeholder"]

  shopping-cart:
    profiles: ["placeholder"]

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: bmw_app
      MYSQL_USER: bmw_user
      MYSQL_PASSWORD: change_me
      MYSQL_ROOT_PASSWORD: change_me_root
    ports:
      - "3306:3306"
    volumes:
      - ./infrastructure/mysql/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio:RELEASE.2025-10-15T17-29-55Z

    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: change_me
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./infrastructure/minio/data:/data
